name: Documentation
on:
  pull_request:
    paths:
      - '.github/workflows/documentation.yml'
      - 'package.json'
      - 'docs/**'
      - 'lib'
      - 'test'
      - 'website.js'
      - 'CHANGELOG.md'
  push:
    branches:
      - master
    paths:
      - '.github/workflows/documentation.yml'
      - 'package.json'
      - 'docs/**'
      - 'lib'
      - 'test'
      - 'website.js'
      - 'CHANGELOG.md'
permissions:
  contents: read

jobs:
  test-documentation:
    runs-on: ubuntu-20.04
    name: Test Generating Docs
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3

      - name: Setup node
        uses: actions/setup-node@969bd2663942d722d85b6a8626225850c2f7be4b # v3.5.0
        with:
          node-version: 16

      - run: npm install
      - run: npm run docs:clean
      - run: npm run docs:generate
